name: Feature request
description: Suggest an improvement or a feature
title: "[FEATURE]: "
labels: ["enhancement"]
body:
- type: textarea
  id: featuredesc
  attributes:
    label: Feature Description
    description: A general description of the feature
  validations:
    required: true
- type: textarea
  id: featuresteps
  attributes:
    label: Steps how to use this feature
    description: A step by step list how to utilize this feature. How exactly do you imagine users use it and what result they can expect?
    value: |
      1.
      2.
      3.
      ...
    render: bash
  validations:
    required: false
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/PixiEditor/PixiEditor/blob/master/CODE_OF_CONDUCT.md). 
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
